// simple error catching.
try {
    console.log(notVar)
}
catch {
    console.log('An error has occured.')
}
finally {
    console.log('Done.')
} 
// pretty self explanatory